### ISSUE TITLE
How to store templates?

### ISSUE THREAD

**Issue by dudektria** [dudektria/pnictogen#4]
Templates in `examples/templates` might be too complex. My plan is to create some kind of repository (https://github.com/dudektria/pnictogen-templates) of complex, specific templates and restrict the examples in `examples/templates` to simple tests.

**Comment by berquist** [comment]
In principle this is a good idea. It may depend partially on whether or not you want to test all templates. From experience, testing data that lives outside the repository is more difficult. It is probably also more important once the number of templates grows.

Do you have a lot of complex templates already that you can populate the second repository with?

**Comment by dudektria** [comment]
I'm thinking about testing based on features, but not templates. What do you think?

Yes, I have some complex templates already, but not many.

**Comment by dudektria** [comment]
I opted to keep all templates within this repository, in a single directory (`/repo`) (f63009d7e2f29f8965e656c861793cf995f177ee).

I'm closing this now, but feel free to reopen it if needed.
